export const endpoints = {
  home: {
    summary: '/home',
    heroSlides: '/home/hero-slides',
    trendingSearches: '/search/trending',
    featuredCategories: '/categories',
    testimonials: '/testimonials',
    genreHighlights: '/home/genres/highlights',
  },
  books: {
    list: '/books/',
    categories: '/books/categories/',
    dashboardList: '/books/dashboard/',
    dashboardCategories: '/books/dashboard/categories/',
    authorDetail: (authorSlug: string) => `/books/authors/${authorSlug}/`,
    authorOfWeek: '/books/author-of-the-week/',
    booksOfYear: '/books/books-of-the-year/',
    bestSelling: '/books/best-selling/',
    detail: (bookSlug: string) => `/books/${bookSlug}/`,
    likes: (bookSlug: string) => `/books/${bookSlug}/likes/`,
  },
  printing: {
    categories: '/printing/categories/',
    categoryItems: (categoryId: string) => `/printing/categories/${categoryId}/items/`,
    requests: '/printing/requests/',
    requestDetail: (requestId: string) => `/printing/requests/${requestId}/`,
    estimate: '/printing/requests/estimate/',
    uploads: '/printing/uploads/presign/',
  },
  contact: {
    info: '/contact/info',
    subjects: '/contact/subjects',
    availability: '/contact/availability',
    messages: '/contact/messages',
    dashboardMessages: '/contact/dashboard/messages',
    messageDetail: (messageId: string) => `/contact/messages/${messageId}`,
  },
  auth: {
    login: '/auth/login/',
  },
  dashboard: {
    overview: '/dashboard/overview/',
    revenue: '/dashboard/revenue/',
    retention: '/dashboard/retention/',
    leads: '/dashboard/leads/',
    orders: '/dashboard/orders/',
    books: '/dashboard/books/',
    notifications: '/dashboard/notifications/',
    calendar: '/dashboard/calendar/',
    favorites: '/dashboard/favorites/',
  },
  search: {
    suggestions: '/search/suggestions',
  },
  cart: {
    summary: '/cart/summary',
  },
} as const;
